# Generated by Django 4.1.7 on 2023-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_alter_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="total_itens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
