# Generated by Django 4.1.7 on 2023-03-08 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_cartproduct_total_itens_cartproduct_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="total_itens",
        ),
    ]
