# Generated by Django 4.1.7 on 2023-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_remove_cartproduct_total_itens"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="total_itens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
