# Generated by Django 4.1.7 on 2023-03-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_cartproduct_total_itens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="total_itens",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
