# Generated by Django 4.1.7 on 2023-03-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0006_alter_cartproduct_total_itens"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
