# Generated by Django 4.1.7 on 2023-03-08 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product",
        ),
    ]
