# Generated by Django 4.1.7 on 2023-03-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_remove_category_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
